---
- hosts: default_target
  become: yes
  tasks:
  - name: create backup copy of original file
    copy:
      remote_src: yes
      force: no
      mode: preserve
      src: /etc/default/grub
      dest: /etc/default/grub.orig
  - name: remove rhbg quiet from kernel params in default grub config
    lineinfile:
      path: /etc/default/grub
      regexp: '(?P<begin>^GRUB_CMDLINE_LINUX="[A-Za-z0-9=\- ]*?)(?P<to_rm> rhgb quiet)?(?P<end>"$)'
      line: '\g<begin>\g<end>'
      #line: '\1\3' # alternatively, this would work
      backrefs: yes
    notify: update grub cfg
  handlers:
  # run grub2-mkconfig command to update grub config
  - name: update grub cfg
    command:
      cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
...
