---
- hosts: default_target
  become: yes
  tasks:
  - name: update all packages using dnf
    dnf:
      name: "*"
      state: latest
    notify:
    - check reboot
    - reboot
  handlers:
  # check if computer needs to be rebooted
  - name: check reboot
    command:
      cmd: dnf needs-restarting -r
      warn: false # suppress dnf module warning
    register: needs_restarting
    changed_when: false
    failed_when: needs_restarting.rc not in [0,1]
  - name: reboot
    reboot:
    when:
    - needs_restarting.rc == 1
...
